const guzikBlbBookSlugs: Record<string, string> = {
  genesis: "genesis",
  exodus: "exodus",
  leviticus: "leviticus",
  numbers: "numbers",
  deuteronomy: "deuteronomy",
  joshua: "joshua",
  judges: "judges",
  ruth: "ruth",
  "1-samuel": "1-samuel",
  "1samuel": "1-samuel",
  "2-samuel": "2-samuel",
  "2samuel": "2-samuel",
  "1-kings": "1-kings",
  "1kings": "1-kings",
  "2-kings": "2-kings",
  "2kings": "2-kings",
  "1-chronicles": "1-chronicles",
  "1chronicles": "1-chronicles",
  "2-chronicles": "2-chronicles",
  "2chronicles": "2-chronicles",
  ezra: "ezra",
  nehemiah: "nehemiah",
  esther: "esther",
  job: "job",
  psalm: "psalms",
  psalms: "psalms",
  proverbs: "proverbs",
  ecclesiastes: "ecclesiastes",
  "song-of-solomon": "song-of-solomon",
  songofsolomon: "song-of-solomon",
  isaiah: "isaiah",
  jeremiah: "jeremiah",
  lamentations: "lamentations",
  ezekiel: "ezekiel",
  daniel: "daniel",
  hosea: "hosea",
  joel: "joel",
  amos: "amos",
  obadiah: "obadiah",
  jonah: "jonah",
  micah: "micah",
  nahum: "nahum",
  habakkuk: "habakkuk",
  zephaniah: "zephaniah",
  haggai: "haggai",
  zechariah: "zechariah",
  malachi: "malachi",
  matthew: "matthew",
  mark: "mark",
  luke: "luke",
  john: "john",
  acts: "acts",
  romans: "romans",
  "1-corinthians": "1-corinthians",
  "1corinthians": "1-corinthians",
  "2-corinthians": "2-corinthians",
  "2corinthians": "2-corinthians",
  galatians: "galatians",
  ephesians: "ephesians",
  philippians: "philippians",
  colossians: "colossians",
  "1-thessalonians": "1-thessalonians",
  "1thessalonians": "1-thessalonians",
  "2-thessalonians": "2-thessalonians",
  "2thessalonians": "2-thessalonians",
  "1-timothy": "1-timothy",
  "1timothy": "1-timothy",
  "2-timothy": "2-timothy",
  "2timothy": "2-timothy",
  titus: "titus",
  philemon: "philemon",
  hebrews: "hebrews",
  james: "james",
  "1-peter": "1-peter",
  "1peter": "1-peter",
  "2-peter": "2-peter",
  "2peter": "2-peter",
  "1-john": "1-john",
  "1john": "1-john",
  "2-john": "2-john",
  "2john": "2-john",
  "3-john": "3-john",
  "3john": "3-john",
  jude: "jude",
  revelation: "revelation",
};

function normalizeBookSlug(bookSlug: string) {
  return bookSlug.trim().toLowerCase().replace(/\s+/g, "-");
}

export function getGuzikBlbStudyGuideUrl(
  bookSlug: string,
  chapter: number
) {
  if (!Number.isInteger(chapter) || chapter < 1) return null;

  const blbSlug = guzikBlbBookSlugs[normalizeBookSlug(bookSlug)];

  if (!blbSlug) return null;

  return `https://www.blueletterbible.org/comm/guzik_david/study-guide/${blbSlug}/${blbSlug}-${chapter}.cfm`;
}
